begin;

alter table public.companies
  drop constraint if exists companies_service_segment_check;

alter table public.companies
  add constraint companies_service_segment_check
  check (service_segment in ('tecnologia', 'otica', 'escola_futebol', 'transportadora', 'generico'));

create table public.transport_vehicles (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id),
  plate text not null,
  renavam text,
  registry_state text not null,
  vehicle_kind text not null check (vehicle_kind in ('tracao', 'reboque', 'utilitario', 'outro')),
  body_type text,
  make text,
  model text,
  model_year integer check (model_year is null or model_year between 1950 and 2200),
  color text,
  rntrc text,
  ownership text not null default 'proprio' check (ownership in ('proprio', 'arrendado', 'terceiro')),
  owner_name text,
  owner_document text,
  tare_kg numeric(14,3) check (tare_kg is null or tare_kg >= 0),
  capacity_kg numeric(14,3) check (capacity_kg is null or capacity_kg >= 0),
  capacity_m3 numeric(14,3) check (capacity_m3 is null or capacity_m3 >= 0),
  odometer_km numeric(14,1) check (odometer_km is null or odometer_km >= 0),
  licensing_expires_at date,
  insurance_expires_at date,
  status text not null default 'ativo' check (status in ('ativo', 'manutencao', 'inativo')),
  notes text,
  created_by uuid references public.profiles(id),
  updated_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (company_id, id),
  unique (company_id, plate)
);

create table public.transport_drivers (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id),
  full_name text not null,
  document text not null,
  cnh_number text not null,
  cnh_category text not null,
  cnh_expires_at date not null,
  phone text,
  email text,
  employment_type text not null default 'proprio' check (employment_type in ('proprio', 'agregado', 'terceiro')),
  status text not null default 'ativo' check (status in ('ativo', 'afastado', 'inativo')),
  emergency_contact text,
  notes text,
  created_by uuid references public.profiles(id),
  updated_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (company_id, id),
  unique (company_id, document),
  unique (company_id, cnh_number)
);

create table public.transport_trips (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id),
  trip_number bigint generated by default as identity,
  client_id uuid,
  sender_client_id uuid,
  recipient_client_id uuid,
  vehicle_id uuid not null,
  trailer_id uuid,
  driver_id uuid not null,
  status text not null default 'planejada' check (status in ('planejada', 'carregamento', 'em_transito', 'entregue', 'cancelada')),
  cargo_description text not null,
  cargo_type text,
  cargo_quantity numeric(14,3) check (cargo_quantity is null or cargo_quantity >= 0),
  gross_weight_kg numeric(14,3) not null default 0 check (gross_weight_kg >= 0),
  cargo_value numeric(14,2) not null default 0 check (cargo_value >= 0),
  freight_value numeric(14,2) not null check (freight_value >= 0),
  toll_value numeric(14,2) not null default 0 check (toll_value >= 0),
  insurance_value numeric(14,2) not null default 0 check (insurance_value >= 0),
  other_costs numeric(14,2) not null default 0 check (other_costs >= 0),
  origin_city text not null,
  origin_state text not null,
  origin_city_code text not null,
  destination_city text not null,
  destination_state text not null,
  destination_city_code text not null,
  scheduled_departure_at timestamptz not null,
  scheduled_arrival_at timestamptz,
  departed_at timestamptz,
  delivered_at timestamptz,
  distance_km numeric(14,1) check (distance_km is null or distance_km >= 0),
  payer_role text not null default 'remetente' check (payer_role in ('remetente', 'destinatario', 'expedidor', 'recebedor', 'outros')),
  operational_notes text,
  created_by uuid references public.profiles(id),
  updated_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (company_id, id),
  unique (company_id, trip_number),
  constraint transport_trips_client_fk foreign key (company_id, client_id) references public.clients(company_id, id),
  constraint transport_trips_sender_fk foreign key (company_id, sender_client_id) references public.clients(company_id, id),
  constraint transport_trips_recipient_fk foreign key (company_id, recipient_client_id) references public.clients(company_id, id),
  constraint transport_trips_vehicle_fk foreign key (company_id, vehicle_id) references public.transport_vehicles(company_id, id),
  constraint transport_trips_trailer_fk foreign key (company_id, trailer_id) references public.transport_vehicles(company_id, id),
  constraint transport_trips_driver_fk foreign key (company_id, driver_id) references public.transport_drivers(company_id, id),
  check (trailer_id is null or trailer_id <> vehicle_id),
  check (scheduled_arrival_at is null or scheduled_arrival_at >= scheduled_departure_at)
);

create table public.transport_trip_documents (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id),
  trip_id uuid not null,
  document_type text not null default 'nfe' check (document_type in ('nfe', 'nf', 'declaracao', 'outro')),
  access_key text,
  number text,
  series text,
  issuer_document text,
  issuer_name text,
  document_value numeric(14,2) check (document_value is null or document_value >= 0),
  gross_weight_kg numeric(14,3) check (gross_weight_kg is null or gross_weight_kg >= 0),
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  constraint transport_trip_documents_trip_fk foreign key (company_id, trip_id) references public.transport_trips(company_id, id) on delete cascade,
  unique (company_id, access_key),
  check (access_key is null or access_key ~ '^[0-9]{44}$')
);

create table public.cte_documents (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id),
  trip_id uuid not null,
  client_id uuid,
  environment text not null default 'homologacao' check (environment in ('homologacao', 'producao')),
  model text not null default '57' check (model = '57'),
  series integer not null default 1 check (series between 1 and 999),
  document_number bigint,
  status text not null default 'rascunho' check (status in ('rascunho', 'validado', 'enfileirado', 'autorizado', 'rejeitado', 'cancelado')),
  modal text not null default 'rodoviario' check (modal in ('rodoviario')),
  service_type text not null default 'normal' check (service_type in ('normal', 'subcontratacao', 'redespacho', 'redespacho_intermediario', 'multimodal')),
  operation_nature text not null,
  cfop text not null,
  issue_state text not null,
  freight_value numeric(14,2) not null check (freight_value >= 0),
  amount_receivable numeric(14,2) not null check (amount_receivable >= 0),
  components jsonb not null default '[]'::jsonb,
  sender_data jsonb not null default '{}'::jsonb,
  recipient_data jsonb not null default '{}'::jsonb,
  payer_data jsonb not null default '{}'::jsonb,
  cargo_data jsonb not null default '{}'::jsonb,
  tax_data jsonb not null default '{}'::jsonb,
  access_key text,
  protocol text,
  rejection_message text,
  request_payload jsonb,
  response_payload jsonb,
  authorized_xml text,
  issued_at timestamptz,
  canceled_at timestamptz,
  created_by uuid references public.profiles(id),
  updated_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (company_id, id),
  constraint cte_documents_trip_fk foreign key (company_id, trip_id) references public.transport_trips(company_id, id),
  constraint cte_documents_client_fk foreign key (company_id, client_id) references public.clients(company_id, id),
  unique (company_id, series, document_number),
  unique (company_id, access_key),
  check (access_key is null or access_key ~ '^[0-9]{44}$')
);

alter table public.financial_entries add column transport_trip_id uuid;
alter table public.financial_entries add column cte_document_id uuid;
alter table public.financial_entries
  add constraint financial_entries_transport_trip_company_fk
  foreign key (company_id, transport_trip_id) references public.transport_trips(company_id, id);
alter table public.financial_entries
  add constraint financial_entries_cte_company_fk
  foreign key (company_id, cte_document_id) references public.cte_documents(company_id, id);

alter table public.payables add column transport_trip_id uuid;
alter table public.payables
  add constraint payables_transport_trip_company_fk
  foreign key (company_id, transport_trip_id) references public.transport_trips(company_id, id);

create index transport_vehicles_company_status_idx on public.transport_vehicles(company_id, status, plate);
create index transport_drivers_company_status_idx on public.transport_drivers(company_id, status, full_name);
create index transport_trips_company_status_date_idx on public.transport_trips(company_id, status, scheduled_departure_at desc);
create index transport_trip_documents_trip_idx on public.transport_trip_documents(company_id, trip_id);
create index cte_documents_company_status_idx on public.cte_documents(company_id, status, created_at desc);
create index financial_entries_transport_trip_idx on public.financial_entries(company_id, transport_trip_id);
create index payables_transport_trip_idx on public.payables(company_id, transport_trip_id);

alter table public.transport_vehicles enable row level security;
alter table public.transport_drivers enable row level security;
alter table public.transport_trips enable row level security;
alter table public.transport_trip_documents enable row level security;
alter table public.cte_documents enable row level security;

create policy transport_vehicles_company_access on public.transport_vehicles
for all to authenticated using (public.company_match(company_id)) with check (public.company_match(company_id));
create policy transport_drivers_company_access on public.transport_drivers
for all to authenticated using (public.company_match(company_id)) with check (public.company_match(company_id));
create policy transport_trips_company_access on public.transport_trips
for all to authenticated using (public.company_match(company_id)) with check (public.company_match(company_id));
create policy transport_trip_documents_company_access on public.transport_trip_documents
for all to authenticated using (public.company_match(company_id)) with check (public.company_match(company_id));
create policy cte_documents_company_access on public.cte_documents
for all to authenticated using (public.company_match(company_id)) with check (public.company_match(company_id));

insert into public.permissions (module, action, scope)
select module, action, 'company'
from (
  values
    ('transporte.frota', 'visualizar'), ('transporte.frota', 'criar'), ('transporte.frota', 'editar'), ('transporte.frota', 'excluir'),
    ('transporte.motoristas', 'visualizar'), ('transporte.motoristas', 'criar'), ('transporte.motoristas', 'editar'), ('transporte.motoristas', 'excluir'),
    ('transporte.viagens', 'visualizar'), ('transporte.viagens', 'criar'), ('transporte.viagens', 'editar'), ('transporte.viagens', 'excluir'),
    ('fiscal.cte', 'visualizar'), ('fiscal.cte', 'criar'), ('fiscal.cte', 'editar'), ('fiscal.cte', 'excluir'), ('fiscal.cte', 'emitir'), ('fiscal.cte', 'cancelar')
) as transport_permissions(module, action)
on conflict (module, action, scope) do nothing;

insert into public.group_permissions (group_id, permission_id)
select group_record.id, permission_record.id
from public.groups group_record
join public.permissions permission_record
  on permission_record.module in ('transporte.frota', 'transporte.motoristas', 'transporte.viagens', 'fiscal.cte')
where group_record.name = 'Master Geral'
   or (group_record.name in ('Administração', 'Administracao') and permission_record.action in ('visualizar', 'criar', 'editar', 'excluir', 'emitir', 'cancelar'))
   or (group_record.name = 'Operação' and permission_record.module like 'transporte.%' and permission_record.action in ('visualizar', 'criar', 'editar'))
   or (group_record.name = 'Fiscal' and permission_record.module = 'fiscal.cte' and permission_record.action in ('visualizar', 'criar', 'editar', 'emitir', 'cancelar'))
   or (group_record.name = 'Financeiro' and permission_record.module in ('transporte.viagens', 'fiscal.cte') and permission_record.action = 'visualizar')
on conflict do nothing;

create or replace function public.seed_transport_permissions_for_group()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  insert into public.group_permissions (group_id, permission_id)
  select new.id, permission_record.id
  from public.permissions permission_record
  where permission_record.module in ('transporte.frota', 'transporte.motoristas', 'transporte.viagens', 'fiscal.cte')
    and (
      new.name = 'Master Geral'
      or (new.name in ('Administração', 'Administracao') and permission_record.action in ('visualizar', 'criar', 'editar', 'excluir', 'emitir', 'cancelar'))
      or (new.name = 'Operação' and permission_record.module like 'transporte.%' and permission_record.action in ('visualizar', 'criar', 'editar'))
      or (new.name = 'Fiscal' and permission_record.module = 'fiscal.cte' and permission_record.action in ('visualizar', 'criar', 'editar', 'emitir', 'cancelar'))
      or (new.name = 'Financeiro' and permission_record.module in ('transporte.viagens', 'fiscal.cte') and permission_record.action = 'visualizar')
    )
  on conflict do nothing;
  return new;
end;
$$;

drop trigger if exists groups_seed_transport_permissions on public.groups;
create trigger groups_seed_transport_permissions
after insert on public.groups
for each row execute function public.seed_transport_permissions_for_group();

commit;
